
import {
  ShieldCheck,
  Code,
  Wrench,
  FlaskConical,
  KeyRound,
  Hash,
  Binary,
  BookType,
  Link,
  Fingerprint,
  MailWarning,
  Network,
  Dna,
  BookUser,
  ScanLine,
  ShieldAlert,
  ServerCog,
  ShieldQuestion,
  GraduationCap,
  FileJson,
  Regex,
  MessageSquare,
  QrCode,
  FingerprintIcon,
  CodeXml,
  Clapperboard,
  Palette,
  Cloud,
  ListOrdered,
  GitFork,
  Shuffle,
  Replace,
  Calculator,
  ScanText,
  Timer,
  BookText,
  LockKeyhole,
  Scale,
  Percent,
  ClipboardList,
  CircleDollarSign,
  Briefcase,
  Eye,
  Key,
  Database,
  Bot,
  FileX,
  FileLock,
  Route,
  Clock,
  Gauge,
  Webhook,
  Orbit,
  GitCompareArrows,
  FileText,
  ScanSearch,
  Smile,
  Sheet as SheetIcon,
  Image,
  Paintbrush,
  UserPlus,
  Scan,
  File,
  Globe,
  ShieldHalf,
} from 'lucide-react';

export type Tool = {
  name: string;
  slug: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category: 'security' | 'developer' | 'general' | 'advanced' | 'data' | 'creative' | 'networking' | 'everyday';
  implemented: boolean;
};

export type ToolCategory = {
  name: string;
  id: 'security' | 'developer' | 'general' | 'advanced' | 'data' | 'creative' | 'networking' | 'everyday';
  tools: Tool[];
};

export const toolsConfig: ToolCategory[] = [
  {
    name: 'Security & Privacy',
    id: 'security',
    tools: [
      { name: 'Password Strength Checker', slug: 'password-strength-checker', description: 'Evaluate password strength.', icon: KeyRound, category: 'security', implemented: true },
      { name: 'Password Breach Checker', slug: 'password-breach-checker', description: 'Check if a password is in a data breach.', icon: ShieldHalf, category: 'security', implemented: true },
      { name: '2FA Code Generator', slug: '2fa-generator', description: 'Generate TOTP/HOTP codes.', icon: Key, category: 'security', implemented: true },
      { name: 'Hash Generator', slug: 'hash-generator', description: 'Generate MD5, SHA1, SHA256 hashes.', icon: Hash, category: 'security', implemented: true },
      { name: 'File/Folder Encryption', slug: 'file-encryption', description: 'Encrypt files with a password.', icon: FileLock, category: 'security', implemented: true },
      { name: 'Metadata Remover', slug: 'metadata-remover', description: 'Strip EXIF data from images.', icon: FileX, category: 'security', implemented: true },
      { name: 'Secure Notes', slug: 'secure-notes', description: 'Client-side encrypted notes.', icon: LockKeyhole, category: 'security', implemented: true },
      { name: 'Phishing Simulator', slug: 'phishing-simulator', description: 'Educational phishing simulation.', icon: MailWarning, category: 'security', implemented: true },
      { name: 'Vulnerability Scanner', slug: 'vulnerability-scanner', description: 'Scan for web vulnerabilities (simulated).', icon: ShieldAlert, category: 'security', implemented: true },
      { name: 'Firewall Simulator', slug: 'firewall-simulator', description: 'Simulate firewall configurations.', icon: ServerCog, category: 'security', implemented: true },
      { name: 'Packet Sniffer', slug: 'packet-sniffer', description: 'Analyze network packets (simulated).', icon: ShieldQuestion, category: 'security', implemented: true },
    ],
  },
   {
    name: 'Networking & Web',
    id: 'networking',
    tools: [
      { name: 'IP Info Viewer', slug: 'ip-info-viewer', description: 'View information about an IP address.', icon: Network, category: 'networking', implemented: true },
      { name: 'DNS Lookup', slug: 'dns-lookup', description: 'Perform DNS lookups.', icon: Dna, category: 'networking', implemented: true },
      { name: 'WHOIS Lookup', slug: 'whois-lookup', description: 'Perform WHOIS lookups.', icon: BookUser, category: 'networking', implemented: true },
      { name: 'Port Scanner', slug: 'port-scanner', description: 'Scan for open ports (simulated).', icon: ScanLine, category: 'networking', implemented: true },
      { name: 'SSL/TLS Checker', slug: 'ssl-tls-checker', description: 'Check SSL/TLS certificate details (simulated).', icon: ShieldCheck, category: 'networking', implemented: true },
      { name: 'Traceroute Visualizer', slug: 'traceroute-visualizer', description: 'Visualize internet path hops (simulated).', icon: Route, category: 'networking', implemented: true },
      { name: 'Ping & Latency Tester', slug: 'ping-tester', description: 'Check connectivity and response time.', icon: Gauge, category: 'networking', implemented: true },
      { name: 'WebSocket Tester', slug: 'websocket-tester', description: 'Test real-time socket connections.', icon: Webhook, category: 'networking', implemented: true },
      { name: 'CORS Tester', slug: 'cors-tester', description: 'Simulate cross-origin requests.', icon: Orbit, category: 'networking', implemented: true },
      { name: 'REST API Tester', slug: 'api-tester', description: 'Send HTTP requests to APIs.', icon: Cloud, category: 'networking', implemented: true },
      { name: 'URL Encoder/Decoder', slug: 'url-encoder-decoder', description: 'Encode/decode URL components.', icon: Link, category: 'networking', implemented: true },
      { name: 'User-Agent Parser', slug: 'user-agent-parser', description: 'Parse User-Agent strings.', icon: Fingerprint, category: 'networking', implemented: true },
    ],
  },
  {
    name: 'Developer Utilities',
    id: 'developer',
    tools: [
      { name: 'JSON Formatter', slug: 'json-formatter', description: 'Beautify or minify JSON data.', icon: FileJson, category: 'developer', implemented: true },
      { name: 'Base64 Encoder/Decoder', slug: 'base64-encoder-decoder', description: 'Encode/decode Base64 strings.', icon: Binary, category: 'developer', implemented: true },
      { name: 'Regex Tester', slug: 'regex-tester', description: 'Test regular expressions.', icon: Regex, category: 'developer', implemented: true },
      { name: 'Regex Generator (AI)', slug: 'regex-generator', description: 'Generate regex from natural language.', icon: Bot, category: 'developer', implemented: true },
      { name: 'AI Code Explainer', slug: 'ai-code-explainer', description: 'Explain code and find vulnerabilities.', icon: Bot, category: 'developer', implemented: true },
      { name: 'AI Code Refactorer', slug: 'code-refactorer', description: 'Optimize code with AI.', icon: Bot, category: 'developer', implemented: true },
      { name: 'Code Diff Checker', slug: 'diff-checker', description: 'Compare two code snippets.', icon: GitCompareArrows, category: 'developer', implemented: true },
      { name: 'Markdown Previewer', slug: 'markdown-previewer', description: 'Live render Markdown.', icon: FileText, category: 'developer', implemented: true },
      { name: 'Cron Expression Builder', slug: 'cron-builder', description: 'Build & test cron jobs visually.', icon: Clock, category: 'developer', implemented: true },
      { name: 'JWT Decoder', slug: 'jwt-decoder', description: 'Decode JSON Web Tokens.', icon: Clapperboard, category: 'developer', implemented: true },
      { name: 'Code Snippet Manager', slug: 'snippet-manager', description: 'Save and manage code snippets.', icon: ListOrdered, category: 'developer', implemented: true },
      { name: 'Git Cheat Sheet', slug: 'git-cheat-sheet', description: 'Quick reference for Git commands.', icon: GitFork, category: 'developer', implemented: true },
      { name: 'HTML Entities', slug: 'html-entities', description: 'Encode/decode HTML entities.', icon: CodeXml, category: 'developer', implemented: true },
      { name: 'Caesar Cipher', slug: 'caesar-cipher', description: 'Simple substitution cipher.', icon: Key, category: 'developer', implemented: true },
      { name: 'UUID Generator', slug: 'uuid-generator', description: 'Generate UUIDs.', icon: FingerprintIcon, category: 'developer', implemented: true },
    ],
  },
  {
    name: 'Data & Analysis',
    id: 'data',
    tools: [
      { name: 'Data Format Converter', slug: 'data-converter', description: 'Convert between CSV, JSON, etc.', icon: Shuffle, category: 'data', implemented: true },
      { name: 'CSV/Excel Analyzer', slug: 'csv-analyzer', description: 'Get quick insights from CSV files.', icon: SheetIcon, category: 'data', implemented: true },
      { name: 'Log Analyzer', slug: 'log-analyzer', description: 'Parse logs for errors with AI.', icon: ScanSearch, category: 'data', implemented: true },
      { name: 'Text Similarity Checker', slug: 'text-similarity', description: 'Compare two documents for plagiarism.', icon: GitCompareArrows, category: 'data', implemented: true },
      { name: 'Sentiment Analyzer', slug: 'sentiment-analyzer', description: 'Analyze the tone of text.', icon: Smile, category: 'data', implemented: true },
      { name: 'Word/Character Counter', slug: 'word-counter', description: 'Count words and characters in text.', icon: ScanText, category: 'data', implemented: true },
    ],
  },
  {
    name: 'Creative & Fun',
    id: 'creative',
    tools: [
       { name: 'Meme Generator', slug: 'meme-generator', description: 'Quickly caption images.', icon: Image, category: 'creative', implemented: true },
       { name: 'ASCII Art Generator (AI)', slug: 'ascii-art-generator', description: 'Convert images or text to ASCII art.', icon: Bot, category: 'creative', implemented: true },
       { name: 'Pixelate/Blur Tool', slug: 'pixelate-tool', description: 'Censor parts of images.', icon: Paintbrush, category: 'creative', implemented: true },
       { name: 'Palette Extractor', slug: 'palette-extractor', description: 'Extract colors from an image.', icon: Palette, category: 'creative', implemented: true },
       { name: 'Name/Username Generator (AI)', slug: 'name-generator', description: 'Generate creative usernames or brand names.', icon: UserPlus, category: 'creative', implemented: true },
       { name: 'Lorem Ipsum Generator', slug: 'lorem-ipsum-generator', description: 'Generate placeholder text.', icon: MessageSquare, category: 'creative', implemented: true },
    ],
  },
  {
    name: 'Everyday Utilities',
    id: 'everyday',
    tools: [
      { name: 'Scientific Calculator', slug: 'scientific-calculator', description: 'Advanced scientific calculator.', icon: FlaskConical, category: 'everyday', implemented: true },
      { name: 'Age Calculator', slug: 'age-calculator', description: 'Calculate age from date of birth.', icon: Calculator, category: 'everyday', implemented: true },
      { name: 'GPA Calculator', slug: 'gpa-calculator', description: 'Calculate Grade Point Average.', icon: GraduationCap, category: 'everyday', implemented: true },
      { name: 'Unit Converter', slug: 'unit-converter', description: 'Convert between various units.', icon: Scale, category: 'everyday', implemented: true },
      { name: 'Currency Converter', slug: 'currency-converter', description: 'Convert between currencies.', icon: CircleDollarSign, category: 'everyday', implemented: true },
      { name: 'QR Code Generator', slug: 'qr-code-generator', description: 'Generate QR codes.', icon: QrCode, category: 'everyday', implemented: true },
      { name: 'Stopwatch & Timer', slug: 'stopwatch', description: 'Online stopwatch and countdown timer.', icon: Timer, category: 'everyday', implemented: true },
      { name: 'Timezone Converter', slug: 'timezone-converter', description: 'Handy for global coordination.', icon: Globe, category: 'everyday', implemented: true },
      { name: 'Text Cleaner', slug: 'text-cleaner', description: 'Remove extra spaces and newlines.', icon: BookText, category: 'everyday', implemented: true },
      { name: 'Document Scanner (OCR)', slug: 'doc-scanner', description: 'Extract text from images/screenshots.', icon: Scan, category: 'everyday', implemented: true },
      { name: 'PDF Tools', slug: 'pdf-tools', description: 'Merge, split, or compress PDFs.', icon: File, category: 'everyday', implemented: true },
      { name: 'Clipboard Manager', slug: 'clipboard-manager', description: 'History of copied text.', icon: ClipboardList, category: 'everyday', implemented: true },
    ],
  },
  {
    name: 'Advanced & Niche',
    id: 'advanced',
    tools: [
      { name: 'Steganography Encoder', slug: 'steganography-encoder', description: 'Hide text within an image.', icon: Eye, category: 'advanced', implemented: true },
      { name: 'Steganography Decoder', slug: 'steganography-decoder', description: 'Extract text from an image.', icon: Key, category: 'advanced', implemented: true },
      { name: 'File Integrity Checker', slug: 'file-integrity-checker', description: 'Generate and verify file checksums.', icon: Database, category: 'advanced', implemented: true },
      { name: 'Port Binding Visualizer', slug: 'port-visualizer', description: 'Visualize local port usage.', icon: Briefcase, category: 'advanced', implemented: true },
    ],
  },
];
