
import {
  ShieldCheck,
  Code,
  Wrench,
  FlaskConical,
  KeyRound,
  Hash,
  Binary,
  BookType,
  Link,
  Fingerprint,
  MailWarning,
  Network,
  Dna,
  BookUser,
  ScanLine,
  ShieldAlert,
  ServerCog,
  ShieldQuestion,
  GraduationCap,
  FileJson,
  Regex,
  MessageSquare,
  QrCode,
  FingerprintIcon,
  CodeXml,
  Clapperboard,
  Palette,
  Cloud,
  ListOrdered,
  GitFork,
  Shuffle,
  Replace,
  Calculator,
  ScanText,
  Timer,
  BookText,
  LockKeyhole,
  Scale,
  Percent,
  ClipboardList,
  CircleDollarSign,
  Briefcase,
  Eye,
  Key,
  Database,
  Bot,
  FileX,
  FileLock,
  Route,
  Clock,
  Gauge,
  Webhook,
  Orbit,
  GitCompareArrows,
  FileText,
  ScanSearch,
  Smile,
  Sheet as SheetIcon,
  Image,
  Paintbrush,
  UserPlus,
  Scan,
  File,
  Globe,
  ShieldHalf,
  FileImage,
  FileDigit,
  Text,
  AudioLines,
  Mic,
  Barcode,
  Combine,
  HeartPulse,
  Receipt,
  Fuel,
  ShoppingCart,
  CalendarClock,
  Sun,
  ClipboardX,
  Battery,
  Disc,
  Trash,
  Keyboard,
  BookMinus,
  Quote,
  Users,
  Languages,
  BookOpenCheck,
  Dice5,
  Copy,
  BrainCircuit,
  Trophy,
  Scissors,
  Eraser,
  Wand2,
  FileDiff,
  CalendarDays,
  GanttChart,
  Clipboard,
  FileScan,
  FileKey2,
  Cpu,
  Brain,
  Palette as PaletteIcon,
  Newspaper,
  Type,
  Sparkles,
  CaseSensitive,
  SpellCheck,
  Book,
  Notebook,
  Speech,
  Library,
  BookCopy,
  Bitcoin,
  Landmark,
  CookingPot,
  Aperture,
  GalleryVertical,
  ScissorsSquare,
  Video,
  Music,
  MousePointer,
  Contact,
  Wifi,
  AlarmClock,
  Goal,
  Map,
  Lightbulb,
  Gamepad2,
  Puzzle,
  AudioLines as SoundboardIcon,
  FileArchive,
  CopyCheck,
  Files,
  PenSquare,
  Youtube,
  Pocket,
  AtSign,
  Camera,
  LineChart,
  Sigma,
  FlaskRound,
  Atom,
  Table,
  History,
  TrendingUp,
  Wallet,
  TestTube,
  Repeat,
  Share2,
  Component,
  Album,
  Film,
  Layers,
  Terminal,
  FileCheck2,
  Waves
} from 'lucide-react';

export type Tool = {
  name: string;
  slug: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category: string;
  implemented: boolean;
};

export type ToolCategory = {
  name: string;
  id: string;
  tools: Tool[];
};

export const toolsConfig: ToolCategory[] = [
  {
    name: 'Security & Privacy',
    id: 'security',
    tools: [
      { name: 'Password Strength Checker', slug: 'password-strength-checker', description: 'Evaluate password strength.', icon: KeyRound, category: 'security', implemented: true },
      { name: 'Password Breach Checker', slug: 'password-breach-checker', description: 'Check if a password is in a data breach.', icon: ShieldHalf, category: 'security', implemented: true },
      { name: 'Random Password Generator', slug: 'random-password-generator', description: 'Create strong, random passwords.', icon: Key, category: 'security', implemented: true },
      { name: '2FA Code Generator', slug: '2fa-generator', description: 'Generate TOTP/HOTP codes.', icon: Key, category: 'security', implemented: true },
      { name: 'Hash Generator', slug: 'hash-generator', description: 'Generate MD5, SHA1, SHA256 hashes.', icon: Hash, category: 'security', implemented: true },
      { name: 'File Encryption Tool', slug: 'file-encryption', description: 'Encrypt files with a password.', icon: FileLock, category: 'security', implemented: true },
      { name: 'Metadata Remover', slug: 'metadata-remover', description: 'Strip EXIF data from images.', icon: FileX, category: 'security', implemented: true },
      { name: 'Secure Notes', slug: 'secure-notes', description: 'Client-side encrypted notes.', icon: LockKeyhole, category: 'security', implemented: true },
      { name: 'Phishing Simulator', slug: 'phishing-simulator', description: 'Educational phishing simulation.', icon: MailWarning, category: 'security', implemented: true },
      { name: 'Vulnerability Scanner', slug: 'vulnerability-scanner', description: 'Scan for web vulnerabilities (simulated).', icon: ShieldAlert, category: 'security', implemented: true },
      { name: 'Firewall Simulator', slug: 'firewall-simulator', description: 'Simulate firewall configurations.', icon: ServerCog, category: 'security', implemented: true },
      { name: 'Packet Sniffer', slug: 'packet-sniffer', description: 'Analyze network packets (simulated).', icon: ShieldQuestion, category: 'security', implemented: true },
      { name: 'Steganography Encoder', slug: 'steganography-encoder', description: 'Hide a message in an image.', icon: Eye, category: 'security', implemented: true },
      { name: 'Steganography Decoder', slug: 'steganography-decoder', description: 'Extract message from an image.', icon: Key, category: 'security', implemented: true },
    ],
  },
  {
    name: 'Networking & Web',
    id: 'networking',
    tools: [
      { name: 'IP Info Viewer', slug: 'ip-info-viewer', description: 'View information about an IP address.', icon: Network, category: 'networking', implemented: true },
      { name: 'DNS Lookup', slug: 'dns-lookup', description: 'Perform DNS lookups.', icon: Dna, category: 'networking', implemented: true },
      { name: 'WHOIS Lookup', slug: 'whois-lookup', description: 'Perform WHOIS lookups.', icon: BookUser, category: 'networking', implemented: true },
      { name: 'Port Scanner', slug: 'port-scanner', description: 'Scan for open ports (simulated).', icon: ScanLine, category: 'networking', implemented: true },
      { name: 'SSL/TLS Checker', slug: 'ssl-tls-checker', description: 'Check SSL/TLS certificate details (simulated).', icon: ShieldCheck, category: 'networking', implemented: true },
      { name: 'Ping & Latency Tester', slug: 'ping-tester', description: 'Check connectivity and response time.', icon: Gauge, category: 'networking', implemented: true },
      { name: 'REST API Tester', slug: 'api-tester', description: 'Send HTTP requests to APIs.', icon: Cloud, category: 'networking', implemented: true },
      { name: 'URL Encoder/Decoder', slug: 'url-encoder-decoder', description: 'Encode/decode URL components.', icon: Link, category: 'networking', implemented: true },
      { name: 'User-Agent Parser', slug: 'user-agent-parser', description: 'Parse User-Agent strings.', icon: Fingerprint, category: 'networking', implemented: true },
      { name: 'Traceroute Visualizer', slug: 'traceroute-visualizer', description: 'Map internet path hops.', icon: Route, category: 'networking', implemented: true },
      { name: 'WebSocket Tester', slug: 'websocket-tester', description: 'Test real-time socket connections.', icon: Webhook, category: 'networking', implemented: true },
    ],
  },
  {
    name: 'Developer Utilities',
    id: 'developer',
    tools: [
      { name: 'JSON Formatter', slug: 'json-formatter', description: 'Beautify or minify JSON data.', icon: FileJson, category: 'developer', implemented: true },
      { name: 'Base64 Encoder/Decoder', slug: 'base64-encoder-decoder', description: 'Encode/decode Base64 strings.', icon: Binary, category: 'developer', implemented: true },
      { name: 'Regex Tester', slug: 'regex-tester', description: 'Test regular expressions.', icon: Regex, category: 'developer', implemented: true },
      { name: 'AI Code Explainer', slug: 'ai-code-explainer', description: 'Explain code and find vulnerabilities.', icon: Bot, category: 'developer', implemented: true },
      { name: 'JWT Decoder', slug: 'jwt-decoder', description: 'Decode JSON Web Tokens.', icon: Clapperboard, category: 'developer', implemented: true },
      { name: 'Code Snippet Manager', slug: 'snippet-manager', description: 'Save and manage code snippets.', icon: ListOrdered, category: 'developer', implemented: true },
      { name: 'Cheat Sheets Hub', slug: 'cheat-sheets', description: 'Quick reference for commands.', icon: BookCopy, category: 'developer', implemented: true },
      { name: 'HTML Entities', slug: 'html-entities', description: 'Encode/decode HTML entities.', icon: CodeXml, category: 'developer', implemented: true },
      { name: 'Caesar Cipher', slug: 'caesar-cipher', description: 'Simple substitution cipher.', icon: Key, category: 'developer', implemented: true },
      { name: 'UUID Generator', slug: 'uuid-generator', description: 'Generate UUIDs.', icon: FingerprintIcon, category: 'developer', implemented: true },
      { name: 'AI Code Refactorer', slug: 'code-refactorer', description: 'Optimize code with AI.', icon: Wand2, category: 'developer', implemented: true },
      { name: 'Regex Generator (AI)', slug: 'regex-generator', description: 'Generate regex from natural language.', icon: Brain, category: 'developer', implemented: true },
      { name: 'Markdown Previewer', slug: 'markdown-previewer', description: 'Live render Markdown.', icon: SheetIcon, category: 'developer', implemented: true },
      { name: 'Cron Expression Builder', slug: 'cron-builder', description: 'Build & test cron jobs visually.', icon: CalendarDays, category: 'developer', implemented: true },
      { name: 'Code Diff Checker', slug: 'diff-checker', description: 'Compare two code snippets.', icon: FileDiff, category: 'developer', implemented: true },
      { name: 'API Key Vault', slug: 'api-key-vault', description: 'Secure storage for keys.', icon: Pocket, category: 'developer', implemented: true },
      { name: 'Shell Command Runner', slug: 'shell-runner', description: 'Test small shell commands.', icon: Terminal, category: 'developer', implemented: true },
    ]
  },
  {
    name: 'File & Data Handling',
    id: 'file-data',
    tools: [
      { name: 'File Converter Hub', slug: 'file-converter', description: 'Convert between file formats.', icon: FileDigit, category: 'file-data', implemented: true },
      { name: 'Image Resizer', slug: 'image-resizer', description: 'Resize and compress images.', icon: FileImage, category: 'file-data', implemented: true },
      { name: 'Text-to-Speech (TTS)', slug: 'text-to-speech', description: 'Listen to any text in a natural voice.', icon: AudioLines, category: 'file-data', implemented: true },
      { name: 'Speech-to-Text (STT)', slug: 'speech-to-text', description: 'Dictate notes or transcribe recordings.', icon: Mic, category: 'file-data', implemented: true },
      { name: 'Barcode Generator/Scanner', slug: 'barcode-generator', description: 'For products, ISBNs, etc.', icon: Barcode, category: 'file-data', implemented: true },
      { name: 'File Splitter & Joiner', slug: 'file-splitter', description: 'Split and merge large files.', icon: Combine, category: 'file-data', implemented: true },
      { name: 'ZIP/RAR Extractor', slug: 'zip-extractor', description: 'Compress/unzip archives.', icon: FileArchive, category: 'file-data', implemented: true },
      { name: 'Checksum Batch Verifier', slug: 'checksum-verifier', description: 'Check multiple file hashes at once.', icon: CopyCheck, category: 'file-data', implemented: true },
      { name: 'Duplicate File Finder', slug: 'duplicate-finder', description: 'Scan for duplicates by name/content.', icon: Files, category: 'file-data', implemented: true },
      { name: 'Text Compare / Diff Tool', slug: 'text-compare', description: 'Compare two documents line by line.', icon: FileDiff, category: 'file-data', implemented: true },
      { name: 'Clipboard Format Cleaner', slug: 'clipboard-format-cleaner', description: 'Strip styles, paste plain text.', icon: Eraser, category: 'file-data', implemented: true },
      { name: 'Data Converter', slug: 'data-converter', description: 'Convert between JSON and CSV.', icon: Database, category: 'file-data', implemented: true },
      { name: 'File Integrity Checker', slug: 'file-integrity-checker', description: 'Generate and verify checksums.', icon: FileCheck2, category: 'file-data', implemented: true },
    ]
  },
  {
    name: 'Internet & Online Helpers',
    id: 'online-helpers',
    tools: [
      { name: 'Link Shortener', slug: 'link-shortener', description: 'Own branded short links.', icon: Link, category: 'online-helpers', implemented: true },
      { name: 'UTM Builder', slug: 'utm-builder', description: 'Generate tracking URLs.', icon: Youtube, category: 'online-helpers', implemented: true },
      { name: 'Robots.txt/Sitemap Viewer', slug: 'seo-viewer', description: 'SEO quick tools.', icon: FileScan, category: 'online-helpers', implemented: true },
      { name: 'Image to Text (OCR)', slug: 'image-to-text', description: 'Extract text from screenshots.', icon: Camera, category: 'online-helpers', implemented: true },
      { name: 'Fake Email Generator', slug: 'fake-email-generator', description: 'Temporary inbox for sign-ups.', icon: AtSign, category: 'online-helpers', implemented: true },
      { name: 'Summarizer Tool', slug: 'summarizer', description: 'Paste text/URL for a short summary.', icon: BookMinus, category: 'online-helpers', implemented: true },
      { name: 'Link Preview Generator', slug: 'link-preview-generator', description: 'Preview metadata and thumbnails.', icon: Share2, category: 'online-helpers', implemented: true },
      { name: 'Fake Data Generator', slug: 'fake-data-generator', description: 'Generate fake test data.', icon: UserPlus, category: 'online-helpers', implemented: true },
      { name: 'Language Detector', slug: 'language-detector', description: 'Auto-detect text language.', icon: Languages, category: 'online-helpers', implemented: true },
    ]
  },
  {
    name: 'Text & Writing',
    id: 'text-writing',
    tools: [
      { name: 'Word/Character Counter', slug: 'word-counter', description: 'Count words and characters in text.', icon: ScanText, category: 'text-writing', implemented: true },
      { name: 'Text Cleaner', slug: 'text-cleaner', description: 'Remove extra spaces and newlines.', icon: Eraser, category: 'text-writing', implemented: true },
      { name: 'Case Converter', slug: 'case-converter', description: 'Change text casing (upper, lower, etc.).', icon: CaseSensitive, category: 'text-writing', implemented: true },
      { name: 'Typos/Grammar Fixer (AI)', slug: 'grammar-fixer', description: 'Auto-correct spelling and grammar.', icon: SpellCheck, category: 'text-writing', implemented: true },
      { name: 'Synonym Finder', slug: 'synonym-finder', description: 'Find better word choices.', icon: Book, category: 'text-writing', implemented: true },
      { name: 'Text Expander / Snippets', slug: 'text-expander', description: 'Save and reuse quick phrases.', icon: Notebook, category: 'text-writing', implemented: true },
      { name: 'PDF → Speech Reader', slug: 'pdf-speech-reader', description: 'Load a PDF and have it read aloud.', icon: Speech, category: 'text-writing', implemented: true },
    ]
  },
  {
    name: 'Handy Calculators',
    id: 'calculators',
    tools: [
      { name: 'Scientific Calculator', slug: 'scientific-calculator', description: 'Advanced scientific calculator.', icon: FlaskConical, category: 'calculators', implemented: true },
      { name: 'Age Calculator', slug: 'age-calculator', description: 'Calculate age from date of birth.', icon: Calculator, category: 'calculators', implemented: true },
      { name: 'Date Difference Calculator', slug: 'date-difference-calculator', description: 'Days/weeks/months between dates.', icon: CalendarClock, category: 'calculators', implemented: true },
      { name: 'GPA Calculator', slug: 'gpa-calculator', description: 'Calculate Grade Point Average.', icon: GraduationCap, category: 'calculators', implemented: true },
      { name: 'Unit Converter', slug: 'unit-converter', description: 'Convert between various units.', icon: Scale, category: 'calculators', implemented: true },
      { name: 'Currency Converter', slug: 'currency-converter', description: 'Convert between currencies.', icon: CircleDollarSign, category: 'calculators', implemented: true },
      { name: 'Tip & Split Bill Calculator', slug: 'tip-calculator', description: 'For dining and sharing costs.', icon: Receipt, category: 'calculators', implemented: true },
      { name: 'BMI & Health Calculator', slug: 'bmi-calculator', description: 'Calculate BMI and other health metrics.', icon: HeartPulse, category: 'calculators', implemented: true },
      { name: 'Loan / EMI Calculator', slug: 'loan-calculator', description: 'Finance helper for loans.', icon: Landmark, category: 'calculators', implemented: true },
      { name: 'Discount & GST Calculator', slug: 'discount-calculator', description: 'Shopping quick math.', icon: Percent, category: 'calculators', implemented: true },
      { name: 'Cooking Converter', slug: 'cooking-converter', description: 'Cups ↔ grams ↔ ml.', icon: CookingPot, category: 'calculators', implemented: true },
      { name: 'Percentage Calculator', slug: 'percentage-calculator', description: 'Find % increase/decrease.', icon: TrendingUp, category: 'calculators', implemented: true },
    ]
  },
   {
    name: 'Math & Science',
    id: 'math-science',
    tools: [
      { name: 'Graph Plotter', slug: 'graph-plotter', description: 'Plot mathematical functions.', icon: LineChart, category: 'math-science', implemented: true },
      { name: 'Matrix Calculator', slug: 'matrix-calculator', description: 'Determinants, inverses, etc.', icon: Table, category: 'math-science', implemented: true },
      { name: 'Statistics Helper', slug: 'statistics-helper', description: 'Mean, median, std dev.', icon: Sigma, category: 'math-science', implemented: true },
      { name: 'Chemical Equation Balancer', slug: 'chemical-equation-balancer', description: 'Balance chemical equations.', icon: FlaskRound, category: 'math-science', implemented: true },
      { name: 'Periodic Table Explorer', slug: 'periodic-table', description: 'Interactive periodic table.', icon: Atom, category: 'math-science', implemented: true },
      { name: 'Unit Circle & Trig Helper', slug: 'trig-helper', description: 'Quick reference for students.', icon: Sigma, category: 'learning', implemented: true },
      { name: 'Physics Formula Sheet', slug: 'physics-formulas', description: 'Searchable formula library.', icon: Atom, category: 'learning', implemented: true },
    ]
  },
  {
    name: 'Creative & Media',
    id: 'creative',
    tools: [
      { name: 'Lorem Ipsum Generator', slug: 'lorem-ipsum-generator', description: 'Generate placeholder text.', icon: MessageSquare, category: 'creative', implemented: true },
      { name: 'Meme Generator', slug: 'meme-generator', description: 'Create memes with custom text.', icon: Newspaper, category: 'creative', implemented: true },
      { name: 'ASCII Art Generator', slug: 'ascii-art-generator', description: 'Convert images/text to ASCII art.', icon: Type, category: 'creative', implemented: true },
      { name: 'Pixelate/Blur Tool', slug: 'image-censor-tool', description: 'Censor parts of images.', icon: Scissors, category: 'creative', implemented: true },
      { name: 'Palette Extractor', slug: 'palette-extractor', description: 'Extract color palettes from images.', icon: PaletteIcon, category: 'creative', implemented: true },
      { name: 'Name/Username Generator', slug: 'name-generator', description: 'Generate creative usernames.', icon: Sparkles, category: 'creative', implemented: true },
      { name: 'Favicon & Icon Generator', slug: 'favicon-generator', description: 'Make app icons from text/images.', icon: Aperture, category: 'creative', implemented: true },
      { name: 'Image Format Converter', slug: 'image-format-converter', description: 'PNG ↔ JPG ↔ WebP.', icon: GalleryVertical, category: 'creative', implemented: true },
      { name: 'GIF Maker', slug: 'gif-maker', description: 'From images or video clips.', icon: Clapperboard, category: 'creative', implemented: true },
      { name: 'Audio Converter', slug: 'audio-converter', description: 'MP3 ↔ WAV ↔ AAC.', icon: Music, category: 'creative', implemented: true },
      { name: 'Video Cutter/Trimmer', slug: 'video-trimmer', description: 'Quick clip from a video.', icon: ScissorsSquare, category: 'creative', implemented: true },
      { name: 'Music Tone Generator', slug: 'tone-generator', description: 'Frequencies, binaural beats.', icon: Waves, category: 'creative', implemented: true },
      { name: 'ASCII → Emoji Converter', slug: 'ascii-emoji-converter', description: 'Fun stylized text.', icon: Smile, category: 'creative', implemented: true },
      { name: 'Photo Collage Maker', slug: 'collage-maker', description: 'Combine multiple images.', icon: Album, category: 'creative', implemented: true },
      { name: 'Poster/Flyer Generator', slug: 'poster-generator', description: 'Pre-made templates.', icon: PenSquare, category: 'creative', implemented: true },
      { name: 'Audio Effects Tool', slug: 'audio-effects', description: 'Add echo, reverb, etc.', icon: Disc, category: 'creative', implemented: true },
      { name: 'Color Picker', slug: 'color-picker', description: 'Select colors and get their codes.', icon: Palette, category: 'creative', implemented: true },
    ],
  },
  {
    name: 'Device Utilities',
    id: 'device',
    tools: [
      { name: 'Screen Ruler & Color Sampler', slug: 'screen-ruler', description: 'Measure pixels, grab colors.', icon: MousePointer, category: 'device', implemented: true },
      { name: 'Clipboard History with Search', slug: 'clipboard-history', description: 'More powerful than native history.', icon: ClipboardList, category: 'device', implemented: true },
      { name: 'QR/Barcode History', slug: 'scan-history', description: 'Log of scanned codes.', icon: Scan, category: 'device', implemented: true },
      { name: 'Contact vCard Generator', slug: 'vcard-generator', description: 'Make/share digital business cards.', icon: Contact, category: 'device', implemented: true },
      { name: 'File Transfer over Wi-Fi', slug: 'wifi-transfer', description: 'Phone ↔ laptop locally.', icon: Wifi, category: 'device', implemented: true },
      { name: 'Clipboard Cleaner', slug: 'clipboard-cleaner', description: 'Clear clipboard securely.', icon: ClipboardX, category: 'device', implemented: true },
      { name: 'Battery Health Checker', slug: 'battery-health-checker', description: 'Estimate battery cycles & health.', icon: Battery, category: 'device', implemented: true },
      { name: 'Storage Analyzer', slug: 'storage-analyzer', description: 'See large files & space usage.', icon: Disc, category: 'device', implemented: true },
      { name: 'File Shredder', slug: 'file-shredder', description: 'Securely delete sensitive files.', icon: Trash, category: 'device', implemented: true },
      { name: 'Hotkey Launcher', slug: 'hotkey-launcher', description: 'Quick open apps, links, or commands.', icon: Keyboard, category: 'device', implemented: true },
      { name: 'Wi-Fi QR Generator', slug: 'wifi-qr-generator', description: 'Share Wi-Fi credentials easily.', icon: Wifi, category: 'device', implemented: true },
      { name: 'Sensor Tester', slug: 'sensor-tester', description: 'Test gyroscope, etc.', icon: Orbit, category: 'device', implemented: true },
      { name: 'Clipboard Sync (LAN)', slug: 'clipboard-sync', description: 'Sync between devices.', icon: Share2, category: 'device', implemented: true },
      { name: 'Offline File Share (QR)', slug: 'offline-file-share', description: 'Send files via QR codes.', icon: Share2, category: 'device', implemented: true },
      { name: 'Custom Alarm Sounds', slug: 'custom-alarm', description: 'Timers with own audio.', icon: AlarmClock, category: 'device', implemented: true },
    ]
  },
  {
    name: 'Mind & Productivity',
    id: 'productivity',
    tools: [
      { name: 'Pomodoro Timer', slug: 'pomodoro-timer', description: 'Focus and rest cycles.', icon: AlarmClock, category: 'productivity', implemented: true },
      { name: 'Daily Journal / Diary', slug: 'journal', description: 'Quick notes saved offline.', icon: BookText, category: 'productivity', implemented: true },
      { name: 'Habit Tracker', slug: 'habit-tracker', description: 'Streaks and reminders.', icon: Goal, category: 'productivity', implemented: true },
      { name: 'Mind Map Creator', slug: 'mind-map', description: 'Simple node/branch diagrams.', icon: Map, category: 'productivity', implemented: true },
      { name: 'Random Idea Generator', slug: 'idea-generator', description: 'For brainstorming.', icon: Lightbulb, category: 'productivity', implemented: true },
      { name: 'Project Management', slug: 'project-management', description: 'Simple Kanban board.', icon: GanttChart, category: 'productivity', implemented: true },
      { name: 'Shopping List', slug: 'shopping-list', description: 'Minimalist shopping list.', icon: ShoppingCart, category: 'productivity', implemented: true },
      { name: 'Birthday & Reminder Tool', slug: 'reminders', description: 'Store dates, get notifications.', icon: CalendarClock, category: 'productivity', implemented: true },
    ]
  },
  {
    name: 'Learning & Knowledge',
    id: 'learning',
    tools: [
      { name: 'Flashcard Quizzer', slug: 'flashcard-maker', description: 'Test yourself with custom cards.', icon: Repeat, category: 'learning', implemented: true },
      { name: 'Spaced Repetition Scheduler', slug: 'spaced-repetition', description: 'Memory optimization.', icon: History, category: 'learning', implemented: true },
      { name: 'Language Word of the Day', slug: 'word-of-day', description: 'Vocab expansion.', icon: TestTube, category: 'learning', implemented: true },
      { name: 'Offline Encyclopedia', slug: 'encyclopedia', description: 'Quick knowledge lookups.', icon: Library, category: 'learning', implemented: true },
    ]
  },
  {
    name: 'Fun & Novelty',
    id: 'fun-novelty',
    tools: [
      { name: 'Dice Roller & Coin Flip', slug: 'dice-roller', description: 'RNG for quick decisions.', icon: Dice5, category: 'fun-novelty', implemented: true },
      { name: 'Horoscope & Zodiac Info', slug: 'horoscope', description: 'Quick daily fun tool.', icon: Sun, category: 'fun-novelty', implemented: true },
      { name: 'Name Numerology Finder', slug: 'numerology', description: 'Quirky and engaging.', icon: BookOpenCheck, category: 'fun-novelty', implemented: true },
      { name: 'Puzzle Generator', slug: 'puzzle-generator', description: 'Sudoku, crosswords, riddles.', icon: Puzzle, category: 'fun-novelty', implemented: true },
      { name: 'Random Name Picker', slug: 'random-name-picker', description: 'For raffles or lucky draws.', icon: Users, category: 'fun-novelty', implemented: true },
      { name: 'Random Fact / Quote', slug: 'random-fact-quote', description: 'Daily fun and inspiration.', icon: Quote, category: 'fun-novelty', implemented: true },
      { name: 'Soundboard Tool', slug: 'soundboard', description: 'Play quick sound effects.', icon: SoundboardIcon, category: 'fun-novelty', implemented: true },
      { name: 'Mini Games', slug: 'mini-games', description: 'Tic-Tac-Toe, 2048, Snake.', icon: Gamepad2, category: 'fun-novelty', implemented: true },
    ]
  },
];
