
import {
  ShieldCheck,
  Code,
  Wrench,
  FlaskConical,
  KeyRound,
  Hash,
  Binary,
  BookType,
  Link,
  Fingerprint,
  MailWarning,
  Network,
  Dna,
  BookUser,
  ScanLine,
  ShieldAlert,
  ServerCog,
  ShieldQuestion,
  GraduationCap,
  FileJson,
  Regex,
  MessageSquare,
  QrCode,
  FingerprintIcon,
  CodeXml,
  Clapperboard,
  Palette,
  Cloud,
  ListOrdered,
  GitFork,
  Shuffle,
  Replace,
  Calculator,
  ScanText,
  Timer,
  BookText,
  LockKeyhole,
  Scale,
  Percent,
  ClipboardList,
  CircleDollarSign,
  Briefcase,
  Eye,
  Key,
  Database,
  Bot,
  FileX,
  FileLock,
  Route,
  Clock,
  Gauge,
  Webhook,
  Orbit,
  GitCompareArrows,
  FileText,
  ScanSearch,
  Smile,
  Sheet as SheetIcon,
  Image,
  Paintbrush,
  UserPlus,
  Scan,
  File,
  Globe,
  ShieldHalf,
  FileImage,
  FileDigit,
  Text,
  AudioLines,
  Mic,
  Barcode,
  Combine,
  HeartPulse,
  Receipt,
  Fuel,
  ShoppingCart,
  CalendarClock,
  Sun,
  ClipboardX,
  Battery,
  Disc,
  Trash,
  Keyboard,
  BookMinus,
  Quote,
  Users,
   Languages,
  BookOpenCheck,
  Dice5,
  Copy,
  BrainCircuit,
  Trophy,
  Scissors,
  Eraser,
  Wand2,
  FileDiff,
  CalendarDays,
  GanttChart,
  Clipboard,
  FileScan,
  FileKey2,
  Cpu,
  Brain,
  Palette as PaletteIcon,
  Newspaper,
  Type,
  Sparkles,
} from 'lucide-react';

export type Tool = {
  name: string;
  slug: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category: 'security' | 'developer' | 'general' | 'advanced' | 'data' | 'creative' | 'networking' | 'everyday' | 'file-document' | 'system-helpers' | 'smart-helpers' | 'fun-novelty';
  implemented: boolean;
};

export type ToolCategory = {
  name: string;
  id: 'security' | 'developer' | 'general' | 'advanced' | 'data' | 'creative' | 'networking' | 'everyday' | 'file-document' | 'system-helpers' | 'smart-helpers' | 'fun-novelty';
  tools: Tool[];
};

export const toolsConfig: ToolCategory[] = [
  {
    name: 'Security & Privacy',
    id: 'security',
    tools: [
      { name: 'Password Strength Checker', slug: 'password-strength-checker', description: 'Evaluate password strength.', icon: KeyRound, category: 'security', implemented: true },
      { name: 'Password Breach Checker', slug: 'password-breach-checker', description: 'Check if a password is in a data breach.', icon: ShieldHalf, category: 'security', implemented: true },
      { name: '2FA Code Generator', slug: '2fa-generator', description: 'Generate TOTP/HOTP codes.', icon: Key, category: 'security', implemented: true },
      { name: 'Hash Generator', slug: 'hash-generator', description: 'Generate MD5, SHA1, SHA256 hashes.', icon: Hash, category: 'security', implemented: true },
      { name: 'File/Folder Encryption', slug: 'file-encryption', description: 'Encrypt files with a password.', icon: FileLock, category: 'security', implemented: true },
      { name: 'Metadata Remover', slug: 'metadata-remover', description: 'Strip EXIF data from images.', icon: FileX, category: 'security', implemented: true },
      { name: 'Secure Notes', slug: 'secure-notes', description: 'Client-side encrypted notes.', icon: LockKeyhole, category: 'security', implemented: true },
      { name: 'Phishing Simulator', slug: 'phishing-simulator', description: 'Educational phishing simulation.', icon: MailWarning, category: 'security', implemented: true },
      { name: 'Vulnerability Scanner', slug: 'vulnerability-scanner', description: 'Scan for web vulnerabilities (simulated).', icon: ShieldAlert, category: 'security', implemented: true },
      { name: 'Firewall Simulator', slug: 'firewall-simulator', description: 'Simulate firewall configurations.', icon: ServerCog, category: 'security', implemented: true },
      { name: 'Packet Sniffer', slug: 'packet-sniffer', description: 'Analyze network packets (simulated).', icon: ShieldQuestion, category: 'security', implemented: true },
    ],
  },
   {
    name: 'Networking & Web',
    id: 'networking',
    tools: [
      { name: 'IP Info Viewer', slug: 'ip-info-viewer', description: 'View information about an IP address.', icon: Network, category: 'networking', implemented: true },
      { name: 'DNS Lookup', slug: 'dns-lookup', description: 'Perform DNS lookups.', icon: Dna, category: 'networking', implemented: true },
      { name: 'WHOIS Lookup', slug: 'whois-lookup', description: 'Perform WHOIS lookups.', icon: BookUser, category: 'networking', implemented: true },
      { name: 'Port Scanner', slug: 'port-scanner', description: 'Scan for open ports (simulated).', icon: ScanLine, category: 'networking', implemented: true },
      { name: 'SSL/TLS Checker', slug: 'ssl-tls-checker', description: 'Check SSL/TLS certificate details (simulated).', icon: ShieldCheck, category: 'networking', implemented: true },
      { name: 'Ping & Latency Tester', slug: 'ping-tester', description: 'Check connectivity and response time.', icon: Gauge, category: 'networking', implemented: true },
      { name: 'REST API Tester', slug: 'api-tester', description: 'Send HTTP requests to APIs.', icon: Cloud, category: 'networking', implemented: true },
      { name: 'URL Encoder/Decoder', slug: 'url-encoder-decoder', description: 'Encode/decode URL components.', icon: Link, category: 'networking', implemented: true },
      { name: 'User-Agent Parser', slug: 'user-agent-parser', description: 'Parse User-Agent strings.', icon: Fingerprint, category: 'networking', implemented: true },
    ],
  },
  {
    name: 'Developer Utilities',
    id: 'developer',
    tools: [
      { name: 'JSON Formatter', slug: 'json-formatter', description: 'Beautify or minify JSON data.', icon: FileJson, category: 'developer', implemented: true },
      { name: 'Base64 Encoder/Decoder', slug: 'base64-encoder-decoder', description: 'Encode/decode Base64 strings.', icon: Binary, category: 'developer', implemented: true },
      { name: 'Regex Tester', slug: 'regex-tester', description: 'Test regular expressions.', icon: Regex, category: 'developer', implemented: true },
      { name: 'AI Code Explainer', slug: 'ai-code-explainer', description: 'Explain code and find vulnerabilities.', icon: Bot, category: 'developer', implemented: true },
      { name: 'JWT Decoder', slug: 'jwt-decoder', description: 'Decode JSON Web Tokens.', icon: Clapperboard, category: 'developer', implemented: true },
      { name: 'Code Snippet Manager', slug: 'snippet-manager', description: 'Save and manage code snippets.', icon: ListOrdered, category: 'developer', implemented: true },
      { name: 'Git Cheat Sheet', slug: 'git-cheat-sheet', description: 'Quick reference for Git commands.', icon: GitFork, category: 'developer', implemented: true },
      { name: 'HTML Entities', slug: 'html-entities', description: 'Encode/decode HTML entities.', icon: CodeXml, category: 'developer', implemented: true },
      { name: 'Caesar Cipher', slug: 'caesar-cipher', description: 'Simple substitution cipher.', icon: Key, category: 'developer', implemented: true },
      { name: 'UUID Generator', slug: 'uuid-generator', description: 'Generate UUIDs.', icon: FingerprintIcon, category: 'developer', implemented: true },
    ],
  },
  {
    name: 'Data & Analysis',
    id: 'data',
    tools: [
      { name: 'Data Format Converter', slug: 'data-converter', description: 'Convert between CSV, JSON, etc.', icon: Shuffle, category: 'data', implemented: true },
      { name: 'Word/Character Counter', slug: 'word-counter', description: 'Count words and characters in text.', icon: ScanText, category: 'data', implemented: true },
    ],
  },
   {
    name: 'File & Document Tools',
    id: 'file-document',
    tools: [
        { name: 'File Converter', slug: 'file-converter-placeholder', description: 'Convert between document formats.', icon: FileDigit, category: 'file-document', implemented: true },
        { name: 'Image Resizer', slug: 'image-resizer', description: 'Resize and compress images.', icon: FileImage, category: 'file-document', implemented: true },
        { name: 'Text-to-Speech (TTS)', slug: 'text-to-speech', description: 'Listen to text in a natural voice.', icon: AudioLines, category: 'file-document', implemented: true },
        { name: 'Speech-to-Text (STT)', slug: 'speech-to-text', description: 'Dictate notes or transcribe audio.', icon: Mic, category: 'file-document', implemented: true },
        { name: 'Barcode Generator', slug: 'barcode-placeholder', description: 'Create and read barcodes.', icon: Barcode, category: 'file-document', implemented: true },
        { name: 'File Splitter & Joiner', slug: 'filesplitter-placeholder', description: 'Split and merge large files.', icon: Combine, category: 'file-document', implemented: true },
        { name: 'PDF Tools', slug: 'pdf-tools', description: 'Merge, split, compress, or protect PDFs.', icon: FileText, category: 'file-document', implemented: true },
        { name: 'Document Scanner (OCR)', slug: 'doc-scanner', description: 'Extract text from images/screenshots.', icon: FileScan, category: 'file-document', implemented: true },
    ]
  },
  {
    name: 'Everyday Life Utilities',
    id: 'everyday',
    tools: [
      { name: 'Scientific Calculator', slug: 'scientific-calculator', description: 'Advanced scientific calculator.', icon: FlaskConical, category: 'everyday', implemented: true },
      { name: 'Age Calculator', slug: 'age-calculator', description: 'Calculate age from date of birth.', icon: Calculator, category: 'everyday', implemented: true },
      { name: 'GPA Calculator', slug: 'gpa-calculator', description: 'Calculate Grade Point Average.', icon: GraduationCap, category: 'everyday', implemented: true },
      { name: 'Unit Converter', slug: 'unit-converter', description: 'Convert between various units.', icon: Scale, category: 'everyday', implemented: true },
      { name: 'Currency Converter', slug: 'currency-converter', description: 'Convert between currencies.', icon: CircleDollarSign, category: 'everyday', implemented: true },
      { name: 'QR Code Generator', slug: 'qr-code-generator', description: 'Generate QR codes.', icon: QrCode, category: 'everyday', implemented: true },
      { name: 'Stopwatch & Timer', slug: 'stopwatch', description: 'Online stopwatch and countdown timer.', icon: Timer, category: 'everyday', implemented: true },
      { name: 'Timezone Converter', slug: 'timezone-converter', description: 'Handy for global coordination.', icon: Globe, category: 'everyday', implemented: true },
      { name: 'Text Cleaner', slug: 'text-cleaner', description: 'Remove extra spaces and newlines.', icon: Eraser, category: 'everyday', implemented: true },
      { name: 'BMI & Health Calculator', slug: 'bmi-calculator', description: 'Calculate BMI and other health metrics.', icon: HeartPulse, category: 'everyday', implemented: true },
      { name: 'Tip & Split Bill Calculator', slug: 'tip-calculator', description: 'For dining and sharing costs.', icon: Receipt, category: 'everyday', implemented: true },
      { name: 'Shopping List', slug: 'shopping-list', description: 'A minimal but handy list tracker.', icon: ShoppingCart, category: 'everyday', implemented: true },
      { name: 'Fuel/Mileage Tracker', slug: 'fuel-tracker-placeholder', description: 'Calculate cost efficiency.', icon: Fuel, category: 'everyday', implemented: true },
      { name: 'Birthday & Reminder Tool', slug: 'reminders-placeholder', description: 'Store important dates.', icon: CalendarClock, category: 'everyday', implemented: true },
      { name: 'Weather Widget', slug: 'weather-placeholder', description: 'Minimal forecast via open APIs.', icon: Sun, category: 'everyday', implemented: true },
    ],
  },
  {
    name: 'System & Device Helpers',
    id: 'system-helpers',
    tools: [
        { name: 'Clipboard Manager', slug: 'clipboard-manager', description: 'A history of your copied text.', icon: Clipboard, category: 'system-helpers', implemented: true },
        { name: 'Clipboard Cleaner', slug: 'clipboard-cleaner-placeholder', description: 'Clear clipboard securely.', icon: ClipboardX, category: 'system-helpers', implemented: true },
        { name: 'Battery Health Checker', slug: 'battery-health-placeholder', description: 'Estimate battery cycles & health.', icon: Battery, category: 'system-helpers', implemented: true },
        { name: 'Storage Analyzer', slug: 'storage-analyzer-placeholder', description: 'See large files & space usage.', icon: Disc, category: 'system-helpers', implemented: true },
        { name: 'File Shredder', slug: 'file-shredder-placeholder', description: 'Securely delete sensitive files.', icon: Trash, category: 'system-helpers', implemented: true },
        { name: 'Hotkey Launcher', slug: 'hotkey-launcher-placeholder', description: 'Quick open apps, links, or commands.', icon: Keyboard, category: 'system-helpers', implemented: true },
    ]
  },
   {
    name: 'Smart Online Helpers',
    id: 'smart-helpers',
    tools: [
        { name: 'Summarizer Tool', slug: 'summarizer', description: 'Summarize text or a URL.', icon: BookMinus, category: 'smart-helpers', implemented: true },
        { name: 'Fake Data Generator', slug: 'fake-data-generator', description: 'Generate fake names, emails, etc.', icon: Users, category: 'smart-helpers', implemented: true },
        { name: 'Language Detector', slug: 'language-detector', description: 'Auto-detect the language of text.', icon: Languages, category: 'smart-helpers', implemented: true },
        { name: 'Link Preview Generator', slug: 'link-preview-placeholder', description: 'Preview metadata and thumbnail from a link.', icon: Quote, category: 'smart-helpers', implemented: true },
    ]
  },
  {
    name: 'Creative & Fun',
    id: 'creative',
    tools: [
       { name: 'Lorem Ipsum Generator', slug: 'lorem-ipsum-generator', description: 'Generate placeholder text.', icon: MessageSquare, category: 'creative', implemented: true },
       { name: 'Dice Roller & Coin Flip', slug: 'dice-roller', description: 'RNG for quick decisions.', icon: Dice5, category: 'creative', implemented: true },
       { name: 'Custom Flashcard Maker', slug: 'flashcard-maker', description: 'A helpful tool for studying.', icon: Copy, category: 'creative', implemented: true },
       { name: 'ASCII Art Generator', slug: 'ascii-art-generator', description: 'Convert images or text to ASCII art.', icon: Type, category: 'creative', implemented: false },
       { name: 'Meme Generator', slug: 'meme-generator', description: 'Create memes with custom text.', icon: Newspaper, category: 'creative', implemented: false },
       { name: 'Pixelate/Blur Tool', slug: 'image-censor-tool', description: 'Censor parts of images.', icon: Scissors, category: 'creative', implemented: false },
       { name: 'Palette Extractor', slug: 'palette-extractor', description: 'Extract color palettes from images.', icon: PaletteIcon, category: 'creative', implemented: false },
       { name: 'Name/Username Generator', slug: 'name-generator', description: 'Generate creative usernames.', icon: Sparkles, category: 'creative', implemented: false },
    ],
  },
  {
    name: 'Advanced & Niche',
    id: 'advanced',
    tools: [
      { name: 'Steganography Encoder', slug: 'steganography-encoder', description: 'Hide text within an image.', icon: Eye, category: 'advanced', implemented: true },
      { name: 'Steganography Decoder', slug: 'steganography-decoder', description: 'Extract text from an image.', icon: FileKey2, category: 'advanced', implemented: true },
      { name: 'File Integrity Checker', slug: 'file-integrity-checker', description: 'Generate and verify file checksums.', icon: Database, category: 'advanced', implemented: true },
      { name: 'Port Binding Visualizer', slug: 'port-visualizer', description: 'Visualize local port usage.', icon: Briefcase, category: 'advanced', implemented: true },
      { name: 'Traceroute Visualizer', slug: 'traceroute-visualizer', description: 'Map internet path hops.', icon: Route, category: 'advanced', implemented: false },
      { name: 'WebSocket Tester', slug: 'websocket-tester', description: 'Test real-time socket connections.', icon: Webhook, category: 'advanced', implemented: false },
      { name: 'AI Code Refactorer', slug: 'code-refactorer', description: 'Optimize code with AI.', icon: Wand2, category: 'advanced', implemented: false },
      { name: 'AI Regex Generator', slug: 'regex-generator', description: 'Generate regex from natural language.', icon: Brain, category: 'advanced', implemented: false },
      { name: 'Markdown Previewer', slug: 'markdown-previewer', description: 'Live render Markdown.', icon: SheetIcon, category: 'advanced', implemented: false },
      { name: 'Cron Expression Builder', slug: 'cron-builder', description: 'Build & test cron jobs visually.', icon: CalendarDays, category: 'advanced', implemented: false },
      { name: 'Code Diff Checker', slug: 'diff-checker', description: 'Compare two code snippets.', icon: FileDiff, category: 'advanced', implemented: false },
      { name: 'CSV/Excel Analyzer', slug: 'csv-analyzer', description: 'Get quick insights from spreadsheets.', icon: GanttChart, category: 'advanced', implemented: false },
      { name: 'Log Analyzer', slug: 'log-analyzer', description: 'Parse and analyze log files.', icon: ScanSearch, category: 'advanced', implemented: false },
      { name: 'Text Similarity Checker', slug: 'text-similarity-checker', description: 'Compare documents for plagiarism.', icon: GitCompareArrows, category: 'advanced', implemented: false },
      { name: 'Sentiment Analyzer', slug: 'sentiment-analyzer', description: 'Analyze the tone of text.', icon: Smile, category: 'advanced', implemented: false },
    ],
  },
   {
    name: 'Placeholders (Not Implemented)',
    id: 'fun-novelty',
    tools: [
        { name: 'Horoscope & Zodiac Info', slug: 'horoscope-placeholder', description: 'Quick daily fun tool.', icon: Trophy, category: 'fun-novelty', implemented: true },
        { name: 'Name Numerology Finder', slug: 'numerology-placeholder', description: 'Quirky and engaging.', icon: BookOpenCheck, category: 'fun-novelty', implemented: true },
        { name: 'Puzzle Generator', slug: 'puzzle-generator-placeholder', description: 'Sudoku, crosswords, riddles.', icon: BrainCircuit, category: 'fun-novelty', implemented: true },
    ]
  }
];
